
version: '3.0'
services:
  web:
    # TODO: image, ports and redis dependency
    image wiktor145/io-docker
    ports:
      - "5000:5000"
    depends_on: 
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    # TODO: persistence for redis. You need to persist /data directory.
    ommand: redis-server --appendonly yes
    volumes:
      - ./data:/data
